version: '3'
services:
  nextcloud:
    image: ownyourbits/nextcloud-armhf
    command: "${IP}"
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ncdata:/data
    container_name: nextcloudpi

volumes:
  ncdata:
